

# **Appendix 2 - Effectiveness Monitoring Data and Potential Restoration Site Review** {-#app-eff-mon}

<!--
To update this table:
1. Ensure QGIS project (restoration_wedzin_kwa) is synced and up to date locally
2. Run scripts/gis/amalgamate_field_forms.R to regenerate:
   - /Users/airvine/Projects/gis/restoration_wedzin_kwa/data_field/sites_reviewed_2024_202506.geojson
   - data/gis/sites_reviewed_2024_202506.geojson
3. Rebuild the report
-->

Site locations are available as a downloadable [`sites_reviewed_2024_202506.geojson`](https://github.com/NewGraphEnvironment/restoration_wedzin_kwa_2024/blob/main/data/gis/sites_reviewed_2024_202506.geojson) which renders as an interactive map on GitHub.

```{r tab-ree1-caption, results="asis"}
# Table \@ref(tab:tab-ree1-caption)
my_caption <- ("Results from effectiveness monitoring data collected in 2024 and 2025")
my_tab_caption()
```

```{r citation-convert, eval = FALSE}
# clean up the citations -  just doing this once bc it is really slow!!!
path_gis <- "/Users/airvine/Projects/gis/restoration_wedzin_kwa/data_field/sites_reviewed_2024_202506.geojson"
path_repo <- "data/gis/sites_reviewed_2024_202506.geojson"

dat <- sf::st_read(
  path_repo
)

dat |> 
  sf::st_drop_geometry() |> 
  dplyr::mutate(
    date = as.Date(date_time_start)
  ) |> 
  dplyr::select(
    # date_time_start,
    site_id,
    date,
    reference = citation_key,
    uav_flight,
    works_completed,
    new_site,
    assessment_comment
  ) |> 
  xciter::xct_keys_to_inline_table_col(col_format = "reference") |> 
  #   clean up when NA ends up in citation column
  dplyr::mutate(
    reference = dplyr::if_else(
      reference == "NA",
      "",
      reference
    )
  ) |> 
  # purrr::set_names(~ tools::toTitleCase(gsub("_", " ", .x)))
  readr::write_csv("data/inputs_extracted/monitoring_2024_2025.csv", na = "")

```


```{r tab-ree1}

dat_raw <- readr::read_csv(
  "data/inputs_extracted/monitoring_2024_2025.csv"
) 

dat <- dat_raw |>
  dplyr::mutate(
    type = dplyr::case_when(
      works_completed == "yes" &
        !grepl("mud|kenneth", site_id, ignore.case = TRUE) ~
        "Effectiveness Monitoring",
      
      works_completed == "yes" &
        grepl("mud|kenneth", site_id, ignore.case = TRUE) ~
        "Fraser Site",
      
      
      TRUE ~ "Potential Site"
    ),
    type = factor(type, levels = c("Effectiveness Monitoring", "Potential Site", "Fraser Site"))
  ) |>
  dplyr::mutate(
    assessment_comment = dplyr::case_when(
      reference == "Gottesfeld and Rabnett (2007)" ~
        paste0("Newly proposed site adjacent to traditional fishing site. ", assessment_comment),
      new_site == "yes" ~
        paste0("Newly proposed site. ", assessment_comment),
      TRUE ~ assessment_comment
    ),
    uav_flight = dplyr::if_else(
      uav_flight == "No",
      NA_character_,
      uav_flight
    ) 
  )|> 
  dplyr::arrange(type, site_id) |> 
  dplyr::select(
    site_id,
    date,
    type,
    reference,
    uav_flight,
    assessment_comment
  ) |> 
  tibble::rowid_to_column()

dat |> 
  my_dt_table(cols_freeze_left = 2)
  

```

