#!/usr/bin/env Rscript
#
# lulc_classify.R
#
# Run drift pipeline on the Neexdzii Kwa floodplain AOI generated by
# lulc_network-extract.R. Fetches IO LULC from Planetary Computer,
# classifies, and summarizes land cover by year.
#
# Requires:
#   - data/lulc/floodplain_neexdzii_co.gpkg (from lulc_network-extract.R)
#   - R packages: drift, sf, terra
#
# Output:
#   data/lulc_summary.csv — land cover summary by year (committed)
#
# Relates to #67

library(drift)
library(sf)
library(terra)

terra::terraOptions(threads = 12)

# --- Load floodplain AOI ---
aoi_path <- here::here("data", "lulc", "floodplain_neexdzii_co.gpkg")
stopifnot(file.exists(aoi_path))
aoi <- sf::st_read(aoi_path, quiet = TRUE)
message("AOI: ", round(as.numeric(sf::st_area(aoi)) / 1e6, 1), " km²")

# --- Fetch, classify, summarize ---
rasters <- dft_stac_fetch(aoi, source = "io-lulc", years = c(2017, 2020, 2023))
classified <- dft_rast_classify(rasters, source = "io-lulc")
summary <- dft_rast_summarize(classified, unit = "ha")

# --- Wide format for comparison ---
wide <- summary |>
  dplyr::select(year, class_name, pct) |>
  tidyr::pivot_wider(names_from = year, values_from = pct)

message("\nLand cover change (% of floodplain):")
print(wide)

# --- Save ---
out_path <- here::here("data", "lulc_summary.csv")
readr::write_csv(summary, out_path)
message("\nSaved: ", out_path)
